### ISSUE TITLE
request to a partial matching resource results in Errno::ENOENT

### ISSUE THREAD

**Issue by mblumtritt** [adaoraul/rack-jekyll#27]
Given I have a published file named `_site/test/test.html` and I request to URI `/t` then an Errno::ENOENT will be raised.

The reason is that in jekyll.rb the member `@files` is a string representation of all files and in line 67 a partial matching `path_info` results in `true`. But that's wrong: the string may contain `path_info` but this does not mean that the file exists(!)

I would suggest to check rather if the requested file exists…

**Comment by stomar** [comment]
duplicate of #23.

**Comment by mblumtritt** [comment]
Yes is a duplication. Thanks for your effort!
