### ISSUE TITLE
Please release a new version to rubygems

### ISSUE THREAD

**Issue by gotwalt** [adaoraul/rack-jekyll#33]
0.4.1 (current on rubygems) predates [this commit](https://github.com/adaoraul/rack-jekyll/commit/f4b8e6f57b212831867bd441d14138693a003f61). Without it, rack-jekyll won't run on Heroku due to enforcement of Content-Length headers. If you're getting H25 errors on static assets, this is why.

**Comment by stomar** [comment]
:+1:

Jekyll 2.x is only compatible with 0.3.5, which has a bug concerning Content-Length header calculation. Currently this e.g. truncates most of the delivered files from www.ruby-lang.org.

**Comment by stomar** [comment]
To clarify (see #34): **Please release a new version that is compatible with Jekyll 2, but does not change behaviour.**

**Comment by stomar** [comment]
To clarify (see also #34): Please release a new rack-jekyll version that is **compatible with Jekyll 2** and has recent bug fixes, but **does not change behaviour.**

cc @mattr-

**Comment by lcfg** [comment]
Anyone looking for a quick fix should think about changing your rack-jekyll dependency in your Gemfile to the following: `gem 'rack-jekyll', '~> 0.4.1', :git=>'git://github.com/adaoraul/rack-jekyll.git'`.

This will grab the gem from this github repository instead of rubygems (which is outdated).

**Comment by stomar** [comment]
But note that the current master branch changes behaviour (see 1088b1b615198e33a96a3bb4c601676b62ea59d4) which might cause new problems.

**Comment by nbolten** [comment]
+1

**Comment by stomar** [comment]
0.4.2 has just been released!

Please report any problems you have with the new version.
