### ISSUE TITLE
Do not always regenerate site; crashes on Heroku

### ISSUE THREAD

**Issue by stomar** [adaoraul/rack-jekyll#34]
As far as I understand, rack-jekyll now **always (re)generates** the site (see 1088b1b615198e33a96a3bb4c601676b62ea59d4). **This crashes on Heroku** (read-only file system)!

Besides, also users who do not deploy on Heroku should have the option to avoid regeneration; it's very slow for a big site, so in this case deploying a previously generated site might be the better option.

The default behaviour should IMO be to **not** regenerate an already existing `_site` dir; this is the behaviour of the current (but outdated) RubyGems release, 0.4.1.

Note that we failed to switch www.ruby-lang.org to Jekyll 2 with both of the following approaches:

* use rack-jekyll from RubyGems: in combination with Jekyll 2 this forces a very old version of rack-jekyll (0.3.5, because of dependencies); this version is buggy and truncates files due to wrong Content-Length headers
* use the development branch version from GitHub: this version crashes on Heroku, because of the changed (re)generation behaviour

Please fix this issue and release a new version.

**Comment by stomar** [comment]
See ruby/www.ruby-lang.org/issues/1073.

**Comment by stomar** [comment]
Currently we use a patched version of rack-jekyll 0.4.1 that has more liberal dependencies on Jekyll and rake, see my fork stomar/rack-jekyll. I would prefer switching back to official gem releases some time in the future, though.

**Comment by lcfg** [comment]
Anyone looking for a quick fix should think about changing your rack-jekyll dependency in your Gemfile to the following: `gem 'rack-jekyll', '~> 0.4.1', :git=>'git://github.com/adaoraul/rack-jekyll.git'`.

This will grab the gem from this github repository instead of rubygems (which is outdated).

**Comment by stomar** [comment]
Solved with 0.4.2.
