### ISSUE TITLE
Always displaying “generating pages” message

### ISSUE THREAD

**Issue by remino** [adaoraul/rack-jekyll#4]
When starting rackup, without any options, the Rack application starts and listens on port 9292, but only displays the following message when any HTTP request is sent from the browser:

    This site is currently generating pages. Please reload this page after 10 secs.

````
# config.ru
require "rack/jekyll"
run Rack::Jekyll.new
````

````
# _config.yml
source: ./source
destination: ./public
plugins: ./plugins
markdown: maruku
paginate: 10
````

**Comment by jmccartie** [comment]
@remino Did you ever figure this out? I'm having the same issue on Heroku

**Comment by remino** [comment]
@jmccartie I switched to [Middleman](https://middlemanapp.com/) a while ago, but I use it to build static pages hosted by an old-school Apache server.
